### PR TITLE
Compatibility with latest Phalcon version and minor clean-up

### PR DESCRIPTION
**Pull request by hakimio**
- Fixed `dropTable()` function compatibility with the latest Phalcon version
- Updated logger adapter
- Removed unused code
- Removed commented-out code
- Fixed few variables missing `$`
- Minor code simplification
- Tested the changes on my project

### CODE REVIEW

**Comment by hakimio** [comment]
@kaioken can you review the changes?

**Comment by kaioken** [comment]
@hakimio since this is a update to v5 , we should release 2.0 to avoid issues with people using 1.0

**Comment by hakimio** [comment]
Sounds good to me.

**Review by kaioken — APPROVED** [review]

**Comment by kaioken** [comment]
@hakimio done

**Comment by hakimio** [comment]
Thank you.

PS: you can also change default git branch to `2.x`.

**Comment by kaioken** [comment]
@hakimio done ;)

**Pull request merged**
